---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/1/bookings":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: integer
    post:
      summary: create booking
      tags:
      - Bookings
      parameters: []
      responses:
        '201':
          description: booking created
        '422':
          description: booking must be valid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                time:
                  type: string
                city:
                  type: string
                disease_desc:
                  type: string
                doctor_id:
                  type: integer
                user_id:
                  type: integer
              required:
              - date
              - city
    get:
      summary: list bookings
      tags:
      - Bookings
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: date
                    time:
                      type: text
                    city:
                      type: string
                    disease_desc:
                      type: text
                    doctor_id:
                      type: integer
                    user_id:
                      type: integer
  "/doctors":
    post:
      summary: Creates a doctor
      tags:
      - Doctors
      parameters: []
      responses:
        '201':
          description: doctor created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                city:
                  type: string
                phone:
                  type: integer
                email:
                  type: string
                bio:
                  type: string
                specialization:
                  type: string
                photo:
                  type: string
              required:
              - first_name
              - email
    get:
      summary: List All doctors
      tags:
      - Doctors
      responses:
        '200':
          description: doctors displayed
  "/doctors/{id}":
    get:
      summary: Retrieves a doctor
      tags:
      - Doctors
      - Another Tag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: doctor found
          content:
            application/json:
              schema:
                type: object
                properties:
                  first_name:
                    type: string
                  last_name:
                    type: string
                  city:
                    type: string
                  phone:
                    type: integer
                  email:
                    type: string
                  bio:
                    type: string
                  specialization:
                    type: string
                  photo:
                    type: string
                required:
                - email
                - first_name
                - last_name
            application/xml:
              schema:
                type: object
                properties:
                  first_name:
                    type: string
                  last_name:
                    type: string
                  city:
                    type: string
                  phone:
                    type: integer
                  email:
                    type: string
                  bio:
                    type: string
                  specialization:
                    type: string
                  photo:
                    type: string
                required:
                - email
                - first_name
                - last_name
        '404':
          description: doctor not found
    delete:
      summary: Delete a doctor
      tags:
      - Doctors
      - Another Tag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: doctor deleted
        '404':
          description: blog not found
  "/users":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    get:
      summary: List All users
      tags:
      - Users
      responses:
        '200':
          description: doctors displayed
  "/users/{id}":
    get:
      summary: Retrieves a user
      tags:
      - Users
      - Another Tag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: user found
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                required:
                - name
            application/xml:
              schema:
                type: object
                properties:
                  name:
                    type: string
                required:
                - name
        '404':
          description: user not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
